CREATE TABLE IF NOT EXISTS users (
                         user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email varchar(64),
                         login varchar(64),
                         user_name varchar(64),
                         birthday date
);

CREATE UNIQUE INDEX ON users (email, login);

CREATE TABLE IF NOT EXISTS friendship (
                              user_id int,
                              user_friend_id int,
                              FOREIGN KEY (user_id) REFERENCES users (user_id),
                              FOREIGN KEY (user_friend_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS mpa (
                                     mpa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     mpa_name varchar,
                                     mpa_description varchar
);

CREATE TABLE IF NOT EXISTS films (
                         film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         film_name varchar(200),
                         film_description varchar,
                         release_date date,
                         duration int,
                         mpa_id int,
                         FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS liked (
                         user_id int,
                         film_id int,
                         FOREIGN KEY (user_id) REFERENCES users (user_id),
                         FOREIGN KEY (film_id) REFERENCES films (film_id)
);

CREATE TABLE IF NOT EXISTS genre (
                         genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         genre_name varchar
);

CREATE TABLE IF NOT EXISTS film_genres (
                               film_id int,
                               genre_id int,
                               FOREIGN KEY (film_id) REFERENCES films (film_id),
                               FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);