CREATE TABLE IF NOT EXISTS "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "email" varchar(64),
                         "login" varchar(64),
                         "name" varchar(64),
                         "birthday" date
);

CREATE TABLE IF NOT EXISTS "friendship" (
                              "friendship_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "user_id" int,
                              "user_friend_id" int
);

CREATE TABLE IF NOT EXISTS "films" (
                         "film_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar(200),
                         "description" varchar,
                         "release_date" date,
                         "duration" int,
                         "mpa_id" int
);

CREATE TABLE IF NOT EXISTS "liked" (
                         "like_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "user_id" int,
                         "film_id" int
);

CREATE TABLE IF NOT EXISTS "mpa" (
                       "mpa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       "name" varchar,
                       "description" varchar
);

CREATE TABLE IF NOT EXISTS "genre" (
                         "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar
);

CREATE TABLE IF NOT EXISTS "film_genres" (
                               "film_genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "film_id" int,
                               "genre_id" int
);

ALTER TABLE "friendship" DROP CONSTRAINT IF EXISTS fk_friendship_first_user_id;

ALTER TABLE "friendship" ADD CONSTRAINT fk_friendship_first_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friendship" DROP CONSTRAINT IF EXISTS fk_friendship_second_user_id;

ALTER TABLE "friendship" ADD CONSTRAINT fk_friendship_second_user_id FOREIGN KEY ("user_friend_id") REFERENCES "users" ("user_id");

ALTER TABLE "films" DROP CONSTRAINT IF EXISTS fk_films_mpa;

ALTER TABLE "films" ADD CONSTRAINT fk_films_mpa FOREIGN KEY ("mpa_id") REFERENCES "mpa" ("mpa_id");

ALTER TABLE "liked" DROP CONSTRAINT IF EXISTS fk_liked_user_id;

ALTER TABLE "liked" ADD CONSTRAINT fk_liked_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "liked" DROP CONSTRAINT IF EXISTS fk_liked_film_id;

ALTER TABLE "liked" ADD CONSTRAINT fk_liked_film_id FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "film_genres" DROP CONSTRAINT IF EXISTS fk_film_genres_film_id;

ALTER TABLE "film_genres" ADD CONSTRAINT fk_film_genres_film_id FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "film_genres" DROP CONSTRAINT IF EXISTS fk_film_genres_genre_id;

ALTER TABLE "film_genres" ADD CONSTRAINT fk_film_genres_genre_id FOREIGN KEY ("genre_id") REFERENCES "genre" ("genre_id");